### ISSUE TITLE
Articles showing dummy date of 12/31/1969 in "Last Update" column

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#1832]
**Describe the bug**
Since the most recent update, some of my articles are showing dummy date of 12/31/1969 in "Last Update" column.

**To Reproduce**
Not sure what caused it, but it seemed to appear around when I upgraded to `Version 3.9.3 :fd467d52: (8375)`

I use Inoreader as my feed backend, if that is relevant.

**Screenshots**
<img width="955" alt="image" src="https://github.com/user-attachments/assets/4029b873-d9a3-4803-9bd0-4b8042fc653c">

**Please complete the following information:**
 - Vienna version: `Version 3.9.3 :fd467d52: (8375)`
 - OS version: `14.1.1 (23B81)`

**Additional information:**

**Comment by tonycpsu** [comment]
Downgrading to 3.9.2 seems to fix this, FWIW.

**Comment by TAKeanice** [comment]
Thank you, we thought we had made sure that no default date of 0 (milliseconds after 1.1.1970 00:00 UTC) can appear anywhere. Can you tell us the feed source as well? Then we can make sure that we refine the feature to avoid that behavior.
Can you add the column for creation date and see what that shows in cases when updated date is 0?

**Comment by tonycpsu** [comment]
Feed source is Inoreader -- it seems to affect all of my feeds, not a single RSS source.

Here's what it looks like with 3.9.3 release with published date visible.

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/74b08ecf-098f-4cf4-87e6-887338781d0a">

**Comment by TAKeanice** [comment]
<img width="670" alt="Bildschirmfoto 2024-10-20 um 22 12 17" src="https://github.com/user-attachments/assets/e04c6f36-427c-4bc2-9e5e-4d43d8ab9fde">

Another anomaly here: Date published is later than last update

**Comment by TAKeanice** [comment]
I was not able to find the source of such anomalies. According to the current code, if the feed source does not contain the last update, it is set to the publication date if that exists, or to the date when the article was received. For the publication date, if the feed does not contain it, the updated date (if it exists) or the current date is used, whatever is earlier.

@barijaona, @josh64x2 or @Eitot, maybe you can find a reason for the observed anomalies.

I am not sure about my anomaly, it could have been caused by using a development version of Vienna. @tonycpsu did you use any beta version?

**Comment by joostdekeijzer** [comment]
Not sure if it's related but using `Version 3.9.3 :fd467d52: (8375)` I get the date "01-01-1970, 01:00" for both published as updated dates. The source of the feed seems correct?

I think this only happens after a refresh when an article was already there and is updated?

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/61d0aa2b-fc1e-4cc8-a7c9-ef084639642a">

**Comment by TAKeanice** [comment]
> Not sure if it's related 
It certainly is.

> I get the date "01-01-1970, 01:00" for both published as updated dates. The source of the feed seems correct?
Looks like the source is correct, have to look up whether "pubDate" is taken into account though. The date is the same as in the other cases, "0" but in your time zone.
 
> I think this only happens after a refresh when an article was already there and is updated?

That's a good hint and in my case, I had the same gut feeling but couldn't find the code causing that. I will try another time this weekend.

**Comment by TAKeanice** [comment]
I just realized that the RefreshManager is also manipulating the article dates, which may be causing effects that I have not considered so far.

**Comment by joostdekeijzer** [comment]
Hi TAKeanice,

Just to inform you: with `Version 3.9.4 :498937af: (8382)` I'm still getting reset dates...

From some WordPress blogs I'm following and eg. the example below from which I know it's an updated article.

<img width="1171" alt="Screenshot 2024-10-30 at 10 42 45" src="https://github.com/user-attachments/assets/a335cc1d-3892-466c-84f0-d2d7703f1f29">

**Comment by TAKeanice** [comment]
Hi @joostdekeijzer , thank you for adding that example. I suspect the RefreshManager, which I didn't fix in the last update, is the culprit. I hope to find some time this weekend to figure it out and create a fix.

**Comment by barijaona** [comment]
I just subscribed to https://exiftool.org/rss.xml and I do not reproduce the issue…

<img width="1047" alt="Capture d’écran 2024-10-31 à 21 38 46" src="https://github.com/user-attachments/assets/998a890f-fe92-4e33-98ba-5e7eff90a47b">

**Comment by catxeger** [comment]
Vienna 3.9.4 :49893af: (8382) - I'm seeing this issue regularly with what looks like it may be updated articles as noted above. The dates are sometimes 1969-12-31, and sometimes 1970 (don't have an example to hand). In earlier versions, the provided publication date seemed reasonably appropriate.

![image](https://github.com/user-attachments/assets/6cca8a25-033f-4807-b36e-818f2ac9bc45)

<img width="841" alt="image" src="https://github.com/user-attachments/assets/a5e29527-b9a4-4f46-a350-57d22d2fc813">

**Comment by brianallenlevine** [comment]
If it helps, I've also been encountering "12/31/69, 6:00 PM" dates since a Vienna update or two ago.  They're recur regularly in certain feeds, including these two:

    https://tidbits.com/feed/
    https://blog.documentfoundation.org/feed/

I'm currently using Vienna Version 3.9.4 :498937af: (8382) on a current macOS Sonoma 14.7.1 (23H222).

I'll include a couple screen shots.

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/d9929974-75ab-48fc-8941-1d7bb7d0f66b">

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/eb3e1a6b-a03c-4c61-bfca-c4255ff6f4d7">

(If the screenshots don't appear properly after this comment is posted, I'll try to add them again in a different fashion.)

**Comment by TAKeanice** [comment]
I have done the change I was talking about a couple of weeks ago, it's just waiting to be released. I'd suggest retesting afterwards.

https://github.com/ViennaRSS/vienna-rss/commit/605dc648f54df2c65c484d3faf6aa24ca52159a2

**Comment by joostdekeijzer** [comment]
Sorry to have to report that with `Version 3.9.5 :7784c797: (8414)` I'm still experiencing the issue 😢

**Comment by TAKeanice** [comment]
Can you @brianallenlevine and @joostdekeijzer tell me whether you're seeing this with the old articles that you already received before the upgrade or new ones that were loaded afterwards?

The last update didn't include a script for correction again, and I'm afraid some of the dates of older articles are not salvageable. There's no code any more that I know that would assign strange dates to new articles. That's why it's important for me to know whether the articles with wrong dates are old or new ones.

**Comment by brianallenlevine** [comment]
@TAKeanice, I just looked again at the tidbits and documentfoundation links that I posted screenshots of earlier.  I still saw the "12/31/69, 6:00 PM" dates in both feeds, in at least some of the same old articles.  After this, I unsubscrived and resubscribed both feeds.  In the newly resubscribed feeds, I saw fewer articles, with only valid dates.  

I do have additional feeds with these invalid dates.  Is there perhaps a simpler way of accomplishing an unsubscribe/resubscribe without manually unsubscribing and resubscribing each feed with bad dates?  I've looked, but I'm not seeing anything.

Maybe export all my subscriptions, unsubscribe them all, and then re-import would do the trick?  I don't mind losing unread/read status and such, if I can get rid of the bad dates.

Thanks!

--Brian

**Comment by joostdekeijzer** [comment]
@TAKeanice I'm quite sure it's still happening on new articles. But I did not remove/resubscribe a feed.

See WordPress Core rss feed (Agenda for dec-11 article, published dec-10)

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/93037ba9-e8d8-471d-8d11-7b0658caf5ea" />

**Comment by TAKeanice** [comment]
Thank you @brianallenlevine . Means one more round of investigation, pulling out some more gray hair and hopefully finding the place that still manipulates the dates. Can you post a screenshot?

**Comment by brianallenlevine** [comment]
Here you go, @TAKeanice.  Thanks so much for all your effort on this!

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/5b879db5-8015-4c87-afc0-af4966e234e4" />

**Comment by joostdekeijzer** [comment]
It's hard to test, but I get the impression that this issue has a bigger change of happening on startup when you have "refresh on startup" enabled or when you press the "Refresh all your subscriptions" button.

**Comment by catxeger** [comment]
I'm still seeing the issue with Version 3.9.5 :7784c797: (8414), haven't hit 'refresh all your subscriptions', and it appears to be happening on newly retrieved articles (after 'mark all read' in a given feed). 

Oddly, and visible in the screenshot, one of the articles has the wrong date -- 'Trudeau gave a speech to the Liberals' holiday party — but Freeland stole the show' is showing as '2024-06-23, 08:35', but a check of the website shows 'CBC News · Posted: Dec 18, 2024 3:26 PM EST | Last Updated: 8 hours ago' -- off by nearly 6 months!

![image](https://github.com/user-attachments/assets/0793dcec-dac4-4f26-b72f-cbf002534c89)

**Comment by artcs** [comment]
I'm seeing this issue also on Version 3.9.5 :7784c797: (8414). AFAIKT it happens if an article which existed before is updated with a new published and updated date. Source has correct dates.

![Image](https://github.com/user-attachments/assets/972fd661-a3ec-4088-9122-16b9b6376b50)

**Comment by barijaona** [comment]
I think I found the cause:

in
https://github.com/ViennaRSS/vienna-rss/blob/35bc17e71eda0f5602402b857b578aec6a522c4a/Vienna/Sources/Database/Database.m#L1586

`existingArticle` may be an incomplete version originating from `-minimalCacheForFolder:`, and may therefore have neither `lastUpdate` nor `publicationDate`.

**Comment by TAKeanice** [comment]
> `existingArticle` may be an incomplete version originating from `-minimalCacheForFolder:`

Oh man... I would never have searched in that direction... Let's make sure existingArticle is complete then!

**Comment by barijaona** [comment]
Minimalist approach regarding articles' caching makes completely sense when you may have plenty of feeds to update simultaneously, and you have to handle them in memory rather than on disk. 

We just need to reproduce the date logic which exists in -addArticle:toFolder: to calculate the new last update date.

It would make sense to keep the existing publication date in database.

**Comment by TAKeanice** [comment]
I don't think that loading an article from the DB when an update is saved to the DB anyway is too much of an effort.

**Comment by barijaona** [comment]
It is a waste when you may have to handle tens of thousands of articles at a time during a "Refresh All" and you have the possibility to avoid this. 

Look thoroughly at commit https://github.com/ViennaRSS/vienna-rss/commit/9b4c1261f96746df3cb08583fc8371571f05dc03

**Comment by TAKeanice** [comment]
I'd rather not alter the last update date if we just don't know the original one because we got the ground truth from some cache. It may override semantically relevant information carried by that date. Assume a feed updates that date only for content changes, not for typo corrections - we would update the date anyway.

Maybe we can write a smarter update query that combines the query and the update into one, then no additional time is wasted by a second query.

**Comment by TAKeanice** [comment]
I am thinking about feeds that have a last updated date initially, but an update doesn't have it any more. From what I saw in the code, that's possible for atom feeds for example.

**Comment by barijaona** [comment]
OK. Can you have a look at my updated folderCache branch ?

Especially around https://github.com/barijaona/vienna-rss/blob/750ddedf9d91f6d254b050e701c911ee18bbaa65/Vienna/Sources/Database/Database.m#L1621-L1647

**Comment by barijaona** [comment]
OK. Could you give a look to the updated folderCache branch, especially around https://github.com/barijaona/vienna-rss/blob/8710a064fc4c7b984ff1c21f43b220b2acfb4f7c/Vienna/Sources/Database/Database.m#L1621-L1647 ?

**Comment by barijaona** [comment]
See the logic around https://github.com/barijaona/vienna-rss/blob/08572675ef5f38d69050efd8c72c82f4d3f331db/Vienna/Sources/Database/Database.m#L1619-L1656

**Comment by barijaona** [comment]
Does anybody still has this issue ?

**Comment by joostdekeijzer** [comment]
Yep, eg. my https://www.nrc.nl/rss/ and https://feeds.feedburner.com/9To5Mac-MacAllDay feeds and some WordPress feeds still have this issue.

**Comment by joostdekeijzer** [comment]
It does seem to depend on the number of posts in the feed. I've created a WordPress test site with auto-generated Lorem Ipsum articles. In the feed URL you can configure the number of posts in the feed (within reasonable limits).

With https://feed.dkzr.dev/feed/?posts=50 I hardly get the issue, with https://feed.dkzr.dev/feed/?posts=25 I get it regularly.

**Comment by midnightmagic** [comment]
Turning on "never delete" and subscribing to long-lived or high-volume RSS feeds causes this here too and has for many versions.

e.g. https://www.nhc.noaa.gov/nhc_at1.xml

The current hurricane status is now never at the top of the "Last Update" column. Date Published in this case is, similarly, set to 1969:

<item>
<title>No current storm in NHC Atlantic Wallet 1</title>
<description>No current storm in NHC AT1 as of Mon, 04 Aug 2025 22:50:07 GMT</description>
<pubDate>Mon, 04 Aug 2025 22:50:07 GMT</pubDate>
<link>https://www.nhc.noaa.gov/</link>
<guid>https://www.nhc.noaa.gov/</guid>
<author>nhcwebmaster@noaa.gov (NHC Webmaster)</author>
</item>

-- in spite of pubDate being today. Total articles is 5518. The ability to maintain larger datasets is the primary reason I use Vienna on my desktop. Maybe there's a thread to retrieve the last known date that doesn't complete fast enough, who knows.

**Comment by barijaona** [comment]
I tried the feeds suggested by @joostdekeijzer, especially the test feed with `posts=25`, and the NOAA feed suggested by @midnightmagic, but did not encounter any abnormal dates.

I would appreciate additional details, especially your setting regarding frequency for checking for new articles.

**Comment by joostdekeijzer** [comment]
Hi @barijaona 

> I would appreciate additional details, especially your setting regarding frequency for checking for new articles.

I only check manually...

<img width="612" height="674" alt="Image" src="https://github.com/user-attachments/assets/84dd63aa-6cee-40d1-bb17-7a9ee889d1fa" />

**Comment by barijaona** [comment]
Hi @joostdekeijzer 

I am still unable to reproduce the problem after 11 days of subscription to your  https://feed.dkzr.dev/feed/?posts=25  test feed.

Can you test the following command in Terminal ?
```
sqlite3 ~/Library/Application\ Support/Vienna/messages.db "PRAGMA user_version;" ".exit" 
```

It should report 26

Please try the [latest Beta](https://github.com/ViennaRSS/vienna-rss/releases/tag/v%2F3.10.0_beta5) and provide reference to any new problematic articles from your test feed.

**Comment by joostdekeijzer** [comment]
@barijaona mine reports `25`.

I'll download the beta.

**Comment by joostdekeijzer** [comment]
@barijaona I've installed the beta two days ago. Your SQLite command now returns 26 and it does seem the issue is solved: I haven't had any "wrong dates" since then.

**Comment by midnightmagic** [comment]
Updated to Beta; sqlite3 version reports 26 with the beta. *new* updated RSS seems to no longer get set to a datestamp of 1969; however, old items that had this issue are still sitting at 1969, so the database upgrade didn't correct the historical issue and clean out wrongly-dated items, which makes sense as per below. It corrects even just *updated* entries with the same message_id/etc when it detects an entry gets updated.

It looks like somehow the date and createddate were both set to 0.0 and 0.0 for these broken entries:

select createddate,date from messages where folder_id=6 and date=0.0;
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0
0.0|0.0

Since there is no apparent additional date stamp for these entries where I could use an update query—not even really a clean way to sort by message_id and do an interpolation, *and* these are all *new* entries since my last upgrade (I make backups sometimes of my messages.db) I don't really know how I can properly fix them.

There are many entries where both date and createddate are 0.0:

select count(*) from messages where date=0.0 and createddate=0.0;
2286

There are some where there's a date but no createddate:

select count(*) from messages where createddate=0.0 and date is not 0.0;
9

There are none where there's a createddate but no date:

select count(*) from messages where date=0.0 and createddate is not 0.0;
0

I have Vienna checking for new articles, currently, every 3 hours.

The current release version (and a few versions before that) appears to be the problem.

May I suggest as a robustness measure, you consider two new date fields—updateddate and firstdate which are independent of retrieved data and just filled in automatically when rows are inserted or updated?

**Comment by barijaona** [comment]
@midnightmagic could you clarify which version you were running before ?

Do you use "Mark updated articles as new" in Vienna settings ?

Could you run the following SQL command:
```
select feed_url, count(*) from messages a, rss_folders b where a.folder_id=b.folder_id and createddate=0 group by feed_url;
```
to see if there is a particular pattern?

For privacy reasons, you may send me URLs of some pertinent feeds by email : barijaona at gmail dot com

**Comment by midnightmagic** [comment]
Hello. I was using the version which, at the time I wrote my last comment, said I was "up to date" when I told it to check for updates. At the time I did not have the Beta release channel enabled. I don't know which version that was. The schema reported v25.

I do indeed use "Mark updated articles as new" in settings.

I ran the sqlite3 query you pasted, verbatim, and there is no particular pattern in the results. They vary from news organizations, to forum implicit .rss feeds, to government Tsunami warning feeds, to WHO official feeds.

There are a number of feeds obviously are internal/private. Anyway here're a few:

https://www.smbc-comics.com/comic/rss|7
https://www.who.int/rss-feeds/news-english.xml|19
https://www.osnews.com/feed/|22
https://www.freebsd.org/news/feed.xml|2
https://www.cbc.ca/podcasting/includes/quirksaio.xml|26
https://tools.cdc.gov/api/v2/resources/media/285740.rss|9
http://killsixbilliondemons.com/feed/|23
http://feeds.feedblitz.com/loweringthebar&x=1|45
http://feeds.feedburner.com/PoorlyDrawnLines|56

The total number of individual feeds is sitting around 40 or so.

A good one which updates same-item regularly is the Hurricane watch:

https://www.nhc.noaa.gov/nhc_at1.xml

They update the "No current storm" item I think daily.

A couple that do update historical items regularly—annoyingly—even though things haven't been updated in literally years (not decades, obviously, lol,) is  the wordpress per-blog /feed/ stuff. Really obnoxious.

**Comment by barijaona** [comment]
> Hello. I was using the version which, at the time I wrote my last comment, said I was "up to date" when I told it to check for updates. Athe time I did not have the Beta release channel enabled. I don't know which version that was. The schema reported v25.
> 
It was certainly version 3.9.5

I will soon deliver the "real" 3.10.0 release, which will not differ from Beta 6 on this issue.

I will follow the feeds you listed to try to reproduce the issue. Please advise if you see it happen on __new__ articles.

**Comment by midnightmagic** [comment]
So far so good. I haven't found a way yet to recover the dates on the entries that are no longer on the feeds downloaded without just going through them all manually. I think maybe the information is lost. Thanks for working with me to solve the issue. I rely on Vienna to build an archive of historical RSS feeds, so, the database is currently pretty extensive and to me, pretty valuable.

**Comment by catxeger** [comment]
I've just upgraded to 3.10.0 and I'm still seeing 1969 (I do have 'mark updated articles as new' selected). The feed there is from engadget.com.

<img width="830" height="148" alt="Image" src="https://github.com/user-attachments/assets/e5612c13-2931-4067-96bf-37edfd38a3c1" />

**Comment by barijaona** [comment]
> I've just upgraded to 3.10.0 and I'm still seeing 1969 (I do have 'mark updated articles as new' selected). The feed there is from engadget.com.
> 
Did Vienna 3.10.0 prompt you in order to perform a database upgrade ? Did you accept it ?
