### ISSUE TITLE
Version 3.1.1: Can't permanently unmark articles in the Marked Articles folder

### ISSUE THREAD

**Issue by garynunes** [ViennaRSS/vienna-rss#601]
When displaying the Marked Articles folder's article list I can't get an article to permanently "unmark" itself. When I select an article and either click the marked flag with the mouse or press the "m" key the marked flag disappears from the article but, if I switch to another folder and then back to the Marked Articles folder the articles that I unmarked are still in the folder and they are, once again, marked (context menu's "Mark Unflagged" doesn't work either).

This problem appeared in Version 3.1.1 :7cb6d42. It did not exist in 3.0.9.

Regards,
    Gary Nunes

**Comment by barijaona** [comment]
Fixed in 3.1.2

**Comment by garynunes** [comment]
Just tried 3.1.2. Problem still there. Back to 3.0.9 again.

Regards,
    Gary Nunes

**Comment by barijaona** [comment]
Do you see anything in the logs ?

**Comment by garynunes** [comment]
Opened Vienna 3.1.2. Displayed Marked Articles folder. Unmarked the first two articles and deselected then reselected the Marked Articles folder. The two articles were no longer there (as it should be but different behavior than the last two times I tried this). Again, unmarked the (now different) first two articles, deselected and reselected Marked Articles folder. This time the unmarked articles were still there with the marked flag restored (as I previously observed). Tried again but they won't go away.

Here's the output from the console log during this session. Hope it helps:
4/2/16 7:29:00.842 PM WindowServer[102]: CGXDisableUpdate: UI updates were forcibly disabled by application "Vienna" for over 1.00 seconds. Server has re-enabled them.
4/2/16 7:29:00.946 PM Vienna[29189]: <CATransformLayer: 0x7fabb63a33f0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.947 PM Vienna[29189]: <CATransformLayer: 0x7fabb63a33f0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.947 PM Vienna[29189]: <CATransformLayer: 0x7fabb63a33f0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.947 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c99a0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c99a0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c99a0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb6030730> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.949 PM Vienna[29189]: <CATransformLayer: 0x7fabb6030730> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.949 PM Vienna[29189]: <CATransformLayer: 0x7fabb6030730> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.949 PM Vienna[29189]: <CATransformLayer: 0x7fabb60a4710> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.950 PM Vienna[29189]: <CATransformLayer: 0x7fabb60a4710> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.950 PM Vienna[29189]: <CATransformLayer: 0x7fabb60a4710> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.950 PM Vienna[29189]: <CATransformLayer: 0x7fabb6f76950> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.951 PM Vienna[29189]: <CATransformLayer: 0x7fabb6f76950> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.951 PM Vienna[29189]: <CATransformLayer: 0x7fabb6f76950> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.951 PM Vienna[29189]: <CATransformLayer: 0x7fabb6423460> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb6423460> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb6423460> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb6c55e40> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.953 PM Vienna[29189]: <CATransformLayer: 0x7fabb6c55e40> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.953 PM Vienna[29189]: <CATransformLayer: 0x7fabb6c55e40> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.953 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e8a60> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.956 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e8a60> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.957 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e8a60> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.957 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e91c0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.958 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e91c0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.958 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e91c0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.958 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e7fc0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.959 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e7fc0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.959 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e7fc0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.959 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e9780> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.959 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e9780> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.960 PM Vienna[29189]: <CATransformLayer: 0x7fabb80e9780> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.960 PM Vienna[29189]: <CATransformLayer: 0x7fabb7416500> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.960 PM Vienna[29189]: <CATransformLayer: 0x7fabb7416500> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.961 PM Vienna[29189]: <CATransformLayer: 0x7fabb7416500> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.961 PM Vienna[29189]: <CATransformLayer: 0x7fabb74279b0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.961 PM Vienna[29189]: <CATransformLayer: 0x7fabb74279b0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.962 PM Vienna[29189]: <CATransformLayer: 0x7fabb74279b0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.963 PM Vienna[29189]: <CATransformLayer: 0x7fabb80eb1f0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.963 PM Vienna[29189]: <CATransformLayer: 0x7fabb80eb1f0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.963 PM Vienna[29189]: <CATransformLayer: 0x7fabb80eb1f0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.964 PM Vienna[29189]: <CATransformLayer: 0x7fabb3b00c70> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.964 PM Vienna[29189]: <CATransformLayer: 0x7fabb3b00c70> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.964 PM Vienna[29189]: <CATransformLayer: 0x7fabb3b00c70> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.965 PM Vienna[29189]: <CATransformLayer: 0x7fabb80eff20> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.966 PM Vienna[29189]: <CATransformLayer: 0x7fabb80eff20> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.966 PM Vienna[29189]: <CATransformLayer: 0x7fabb80eff20> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.967 PM Vienna[29189]: <CATransformLayer: 0x7fabb6427780> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.967 PM Vienna[29189]: <CATransformLayer: 0x7fabb6427780> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.967 PM Vienna[29189]: <CATransformLayer: 0x7fabb6427780> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.968 PM Vienna[29189]: <CATransformLayer: 0x7fabb1d0db60> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.968 PM Vienna[29189]: <CATransformLayer: 0x7fabb1d0db60> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.968 PM Vienna[29189]: <CATransformLayer: 0x7fabb1d0db60> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.969 PM Vienna[29189]: <CATransformLayer: 0x7fabb68d96d0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.969 PM Vienna[29189]: <CATransformLayer: 0x7fabb68d96d0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.969 PM Vienna[29189]: <CATransformLayer: 0x7fabb68d96d0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.970 PM Vienna[29189]: <CATransformLayer: 0x7fabb80ee1b0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.970 PM Vienna[29189]: <CATransformLayer: 0x7fabb80ee1b0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.970 PM Vienna[29189]: <CATransformLayer: 0x7fabb80ee1b0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.971 PM Vienna[29189]: <CATransformLayer: 0x7fabb68b4a80> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.971 PM Vienna[29189]: <CATransformLayer: 0x7fabb68b4a80> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.971 PM Vienna[29189]: <CATransformLayer: 0x7fabb68b4a80> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.972 PM Vienna[29189]: <CATransformLayer: 0x7fabb6c333d0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.972 PM Vienna[29189]: <CATransformLayer: 0x7fabb6c333d0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.972 PM Vienna[29189]: <CATransformLayer: 0x7fabb6c333d0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.973 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f0b10> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.973 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f0b10> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.973 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f0b10> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.973 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f6550> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.974 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f6550> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.974 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f6550> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.975 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f6c40> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.975 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f6c40> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.975 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f6c40> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.976 PM Vienna[29189]: <CATransformLayer: 0x7fabb3b2ff60> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.976 PM Vienna[29189]: <CATransformLayer: 0x7fabb3b2ff60> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.976 PM Vienna[29189]: <CATransformLayer: 0x7fabb3b2ff60> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.977 PM Vienna[29189]: <CATransformLayer: 0x7fabb82658a0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.977 PM Vienna[29189]: <CATransformLayer: 0x7fabb82658a0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.977 PM Vienna[29189]: <CATransformLayer: 0x7fabb82658a0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.977 PM Vienna[29189]: <CATransformLayer: 0x7fabb1a2db20> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.978 PM Vienna[29189]: <CATransformLayer: 0x7fabb1a2db20> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.978 PM Vienna[29189]: <CATransformLayer: 0x7fabb1a2db20> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.979 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f7830> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.979 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f7830> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.979 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f7830> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.980 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f8b90> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.980 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f8b90> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.980 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f8b90> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.981 PM Vienna[29189]: <CATransformLayer: 0x7fabb740bbb0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.981 PM Vienna[29189]: <CATransformLayer: 0x7fabb740bbb0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.981 PM Vienna[29189]: <CATransformLayer: 0x7fabb740bbb0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.982 PM Vienna[29189]: <CATransformLayer: 0x7fabb6832840> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.982 PM Vienna[29189]: <CATransformLayer: 0x7fabb6832840> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.982 PM Vienna[29189]: <CATransformLayer: 0x7fabb6832840> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.983 PM Vienna[29189]: <CATransformLayer: 0x7fabb643e490> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.983 PM Vienna[29189]: <CATransformLayer: 0x7fabb643e490> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.983 PM Vienna[29189]: <CATransformLayer: 0x7fabb643e490> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.984 PM Vienna[29189]: <CATransformLayer: 0x7fabb6dc5e30> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.984 PM Vienna[29189]: <CATransformLayer: 0x7fabb6dc5e30> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.984 PM Vienna[29189]: <CATransformLayer: 0x7fabb6dc5e30> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.985 PM Vienna[29189]: <CATransformLayer: 0x7fabb68180f0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.985 PM Vienna[29189]: <CATransformLayer: 0x7fabb68180f0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.985 PM Vienna[29189]: <CATransformLayer: 0x7fabb68180f0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.986 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f8ea0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.986 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f8ea0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.986 PM Vienna[29189]: <CATransformLayer: 0x7fabb80f8ea0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.987 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fa710> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.987 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fa710> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.987 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fa710> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.987 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fa4c0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.988 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fa4c0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.988 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fa4c0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.988 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fb150> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.989 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fb150> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.989 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fb150> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.989 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fbbd0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.989 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fbbd0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.990 PM Vienna[29189]: <CATransformLayer: 0x7fabb80fbbd0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.990 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c25a0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.990 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c25a0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.991 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c25a0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.991 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c0160> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.991 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c0160> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.992 PM Vienna[29189]: <CATransformLayer: 0x7fabb80c0160> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.992 PM Vienna[29189]: <CATransformLayer: 0x7fabb80a1cc0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.992 PM Vienna[29189]: <CATransformLayer: 0x7fabb80a1cc0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.992 PM Vienna[29189]: <CATransformLayer: 0x7fabb80a1cc0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.993 PM Vienna[29189]: <CATransformLayer: 0x7fabb740fee0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.993 PM Vienna[29189]: <CATransformLayer: 0x7fabb740fee0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.993 PM Vienna[29189]: <CATransformLayer: 0x7fabb740fee0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.994 PM Vienna[29189]: <CATransformLayer: 0x7fabb80bf3b0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.994 PM Vienna[29189]: <CATransformLayer: 0x7fabb80bf3b0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.995 PM Vienna[29189]: <CATransformLayer: 0x7fabb80bf3b0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.995 PM Vienna[29189]: <CATransformLayer: 0x7fabb71f52b0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.995 PM Vienna[29189]: <CATransformLayer: 0x7fabb71f52b0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.996 PM Vienna[29189]: <CATransformLayer: 0x7fabb71f52b0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.996 PM Vienna[29189]: <CATransformLayer: 0x7fabb6430960> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.996 PM Vienna[29189]: <CATransformLayer: 0x7fabb6430960> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.996 PM Vienna[29189]: <CATransformLayer: 0x7fabb6430960> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.997 PM Vienna[29189]: <CATransformLayer: 0x7fabb80bcdd0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.997 PM Vienna[29189]: <CATransformLayer: 0x7fabb80bcdd0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.997 PM Vienna[29189]: <CATransformLayer: 0x7fabb80bcdd0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.998 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b7b40> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.998 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b7b40> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.998 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b7b40> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:00.999 PM Vienna[29189]: <CATransformLayer: 0x7fabb1de1080> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:00.999 PM Vienna[29189]: <CATransformLayer: 0x7fabb1de1080> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:00.999 PM Vienna[29189]: <CATransformLayer: 0x7fabb1de1080> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.000 PM Vienna[29189]: <CATransformLayer: 0x7fabb64bad20> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.000 PM Vienna[29189]: <CATransformLayer: 0x7fabb64bad20> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.000 PM Vienna[29189]: <CATransformLayer: 0x7fabb64bad20> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.001 PM Vienna[29189]: <CATransformLayer: 0x7fabb1a48830> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.001 PM Vienna[29189]: <CATransformLayer: 0x7fabb1a48830> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.001 PM Vienna[29189]: <CATransformLayer: 0x7fabb1a48830> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.002 PM Vienna[29189]: <CATransformLayer: 0x7fabb72cee00> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.002 PM Vienna[29189]: <CATransformLayer: 0x7fabb72cee00> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.002 PM Vienna[29189]: <CATransformLayer: 0x7fabb72cee00> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.003 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b5d20> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.003 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b5d20> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.003 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b5d20> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.004 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b3900> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.004 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b3900> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.004 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b3900> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.005 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b2730> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.005 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b2730> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.005 PM Vienna[29189]: <CATransformLayer: 0x7fabb80b2730> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.006 PM Vienna[29189]: <CATransformLayer: 0x7fabb7136410> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.006 PM Vienna[29189]: <CATransformLayer: 0x7fabb7136410> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.006 PM Vienna[29189]: <CATransformLayer: 0x7fabb7136410> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.006 PM Vienna[29189]: <CATransformLayer: 0x7fabb7136450> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:01.007 PM Vienna[29189]: <CATransformLayer: 0x7fabb7136450> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:01.007 PM Vienna[29189]: <CATransformLayer: 0x7fabb7136450> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:01.036 PM WindowServer[102]: reenable_update_for_connection: UI updates were finally reenabled by application "Vienna" after 1.19 seconds (server forcibly re-enabled them after 1.00 seconds)
4/2/16 7:29:04.640 PM Vienna[29189]: <CATransformLayer: 0x7fabb6a54800> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:04.640 PM Vienna[29189]: <CATransformLayer: 0x7fabb6a54800> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:04.645 PM Vienna[29189]: <CATransformLayer: 0x7fabb6a54800> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:06.964 PM Vienna[29189]: <CATransformLayer: 0x7fabb6212330> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:06.964 PM Vienna[29189]: <CATransformLayer: 0x7fabb6212330> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:06.964 PM Vienna[29189]: <CATransformLayer: 0x7fabb6212330> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.944 PM Vienna[29189]: <CATransformLayer: 0x7fabb1ec78d0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.944 PM Vienna[29189]: <CATransformLayer: 0x7fabb1ec78d0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.944 PM Vienna[29189]: <CATransformLayer: 0x7fabb1ec78d0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.945 PM Vienna[29189]: <CATransformLayer: 0x7fabb7be82e0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.945 PM Vienna[29189]: <CATransformLayer: 0x7fabb7be82e0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.945 PM Vienna[29189]: <CATransformLayer: 0x7fabb7be82e0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.946 PM Vienna[29189]: <CATransformLayer: 0x7fabb747c2e0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.946 PM Vienna[29189]: <CATransformLayer: 0x7fabb747c2e0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.946 PM Vienna[29189]: <CATransformLayer: 0x7fabb747c2e0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.947 PM Vienna[29189]: <CATransformLayer: 0x7fabb1dadd10> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.947 PM Vienna[29189]: <CATransformLayer: 0x7fabb1dadd10> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.947 PM Vienna[29189]: <CATransformLayer: 0x7fabb1dadd10> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb62abde0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb62abde0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb62abde0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.948 PM Vienna[29189]: <CATransformLayer: 0x7fabb8053570> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.949 PM Vienna[29189]: <CATransformLayer: 0x7fabb8053570> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.949 PM Vienna[29189]: <CATransformLayer: 0x7fabb8053570> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.950 PM Vienna[29189]: <CATransformLayer: 0x7fabb1d4eaa0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.950 PM Vienna[29189]: <CATransformLayer: 0x7fabb1d4eaa0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.950 PM Vienna[29189]: <CATransformLayer: 0x7fabb1d4eaa0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.951 PM Vienna[29189]: <CATransformLayer: 0x7fabb6bc37e0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.951 PM Vienna[29189]: <CATransformLayer: 0x7fabb6bc37e0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.951 PM Vienna[29189]: <CATransformLayer: 0x7fabb6bc37e0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb80752a0> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb80752a0> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb80752a0> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.952 PM Vienna[29189]: <CATransformLayer: 0x7fabb8015030> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.953 PM Vienna[29189]: <CATransformLayer: 0x7fabb8015030> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.953 PM Vienna[29189]: <CATransformLayer: 0x7fabb8015030> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.953 PM Vienna[29189]: <CATransformLayer: 0x7fabb806f130> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.954 PM Vienna[29189]: <CATransformLayer: 0x7fabb806f130> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.954 PM Vienna[29189]: <CATransformLayer: 0x7fabb806f130> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:07.954 PM Vienna[29189]: <CATransformLayer: 0x7fabb6df5a20> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:07.955 PM Vienna[29189]: <CATransformLayer: 0x7fabb6df5a20> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:07.956 PM Vienna[29189]: <CATransformLayer: 0x7fabb6df5a20> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:10.402 PM Vienna[29189]: <CATransformLayer: 0x7fabb73cbd60> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:10.402 PM Vienna[29189]: <CATransformLayer: 0x7fabb73cbd60> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:10.403 PM Vienna[29189]: <CATransformLayer: 0x7fabb73cbd60> - changing property shadowRadius in transform-only layer, will have no effect
4/2/16 7:29:10.403 PM Vienna[29189]: <CATransformLayer: 0x7fabb73cc950> - changing property shadowOffset in transform-only layer, will have no effect
4/2/16 7:29:10.403 PM Vienna[29189]: <CATransformLayer: 0x7fabb73cc950> - changing property shadowColor in transform-only layer, will have no effect
4/2/16 7:29:10.404 PM Vienna[29189]: <CATransformLayer: 0x7fabb73cc950> - changing property shadowRadius in transform-only layer, will have no effect

**Comment by garynunes** [comment]
FYI, just tried version 3.1.3. No change (i.e., still can't remove articles in Marked Articles folder by unmarking them).

A little more detail:
I keep two copies of Vienna. One is the last version of 3.0.9 which works as expected. The other I keep updating as new versions come out. I just now updated it from 3.1.2 to 3.1.3 and tried unmarking articles in the Marked Articles folder. As before the articles do unmark but, after unselecting and reselecting the folder, the articles remain in the folder and are once again marked. Went back to 3.0.9 and said articles (the first two in this case) can be unmarked and removed. In case it's not obvious the two Viennas share the same database. If I stop running 3.0.9 and start up 3.1.3 the articles removed in 3.0.9 are also now gone in 3.1.3.

Should you need more information let me know (I will try to deliver it as a text file to avoid the last messages verbosity.

Regards,
    Gary Nunes

**Comment by josh64x2** [comment]
@garynunes so when you try and unmark articles in 3.1.3, is 3.0.9 also running at the same time?

**Comment by garynunes** [comment]
No I always quit one before running the other. I'm usually running 3.0.9 since it works for me. I only run the other to update it to the latest version and try it out.

Regards,
    Gary Nunes

**Comment by barijaona** [comment]
Can you check if reindexing database (via the Vienna menu) changes anything ?
Also, it would be interesting to verify : 
- if the articles are still marked after you quit and relaunch the app,
- if the `changing property shadowRadius in transform-only layer` messages appear whatever is chosen in the View-> Layout menu

**Comment by garynunes** [comment]
Reindexing database - no effect.
Quit and relaunch - no effect.
I'm assuming you mean messages in the console? No such messages appear (if you mean somewhere else let me know and I will try again).

Thanks for continuing to look into this.

Regards,
Gary Nunes

**Comment by garynunes** [comment]
FYI, Version 3.1.4 :6ea6f87: no change (regarding my problem).

Regards,
    Gary Nunes

P.S.
Could this could be a Mountain Lion problem (that's the Mac OS I'm currently running)?

**Comment by barijaona** [comment]
Does the log look similar to the 3.1.2’s one ?

**Comment by garynunes** [comment]
I've attached a text file with the 3.1.4 
[consolelog.txt](https://github.com/ViennaRSS/vienna-rss/files/288531/consolelog.txt)
log.

Something (perhaps) interesting happened. When I first started 3.1.4 I unmarked the first two items in the Marked Articles folder and they actually disappeared. However, when I tried to repeat this (unmarking the now new first two items) the items failed to disappear. In other words it worked once and stopped working thereafter. Perhaps this observation along with the 3.1.4 log will help.

Regards,
Gary Nunes

**Comment by barijaona** [comment]
1/ Probably unrelated, but not 100% sure : you seem to have a lot of WebKitPluginHost crashes. I’d suggest doing some cleanup in your `/Library/Internet Plug-Ins/`and `~/Library/Internet Plug-Ins/` folders

2/ Do you have similar problems if you try unmarking the articles not from the “Marked Articles” folder, but from their original folders ?

**Comment by barijaona** [comment]
Another thought : can you check if you have flagged articles in the Trash ?

**Comment by garynunes** [comment]
Regarding Plug-Ins:
Cleaned up some older ones from system area but didn't want to mess with newer ones (post 2010) as worried about screwing something up. There were no plug-ins in user area.
No effect (as far as I can tell) on Vienna (3.0.9 and 3.1.4).

Regarding marking/unmarking articles in original folders:
Works in both Viennas.

Regarding Trash:
Nothing in trash (both Viennas).

Some additional observations:

3.0.9 Vienna:
Clicking on folder shows list scrolled to top (i.e., first item visible at top of list).

3.1.4 Vienna:
Clicking on folder usually shows list scrolled to bottom (i.e., last item visible at bottom of list). I say usually because once it showed top of list, but otherwise has shown bottom.

3.0.9 Vienna:
Selecting an article in an original folder and pressing return to read the article results in the "not read" icon for that article to be removed (in the folder's article list).

3.1.4 Vienna:
Selecting an article in an original folder and pressing return to read the article does NOT remove the "not read" icon from the folder's list. It can be removed manually (and stays removed).

**Comment by johnrclarke** [comment]
I have a possibly related problem in v3.1.5 on OS/X 10.9.5 that occurs on many different feeds with unread articles.  The simplest example I have is a feed with an unread article from 6th May 2016 and another from 20th October 2014 (with many articles in between the two).  When I first select the feed, I can see both unread articles.  If I move down to the next feed then back again, I can only see the first unread article.  The unread count is still two, but I can only view one of them.  The same problem happens on many different feeds with different numbers and ages of unread articles.

Both articles remain visible in the Unread Messages list.

No log messages appear whilst I'm doing this.

The problem isn't restricted to unread articles either.  The first time I select a feed, I can see all the articles, but if I move to another feed then back again, only a smaller number of articles are visible.  I don't know whether it cuts off by age or at a certain number of articles.

This does not happen in Vienna 3.0.9 but every version since then has had problems with articles disappearing from feeds.  I try each new version when it's released but always go back to 3.0.9.

If there's any diagnostics I can run to help figure out the cause, please let me know.  If you think it might help you diagnose the problem, I'm willing to give you a copy of my database.

**Comment by barijaona** [comment]
Yes, a database could help. Zip it, upload it somewhere and send me a link at barijaona dot gmail dot com

**Comment by barijaona** [comment]
@josh64x2 do you still have a 10.8 or 10.9 configuration ? Have you tested it and did you notice something similar ?

**Comment by josh64x2** [comment]
Ohh I do still have one but I haven't tested this issue on it. I will set a reminder

**Comment by barijaona** [comment]
@johnrclarke , can you try the attached build ? I slightly changed the code in order to sync more tightly database and memory updates.
[Viennatest616-678.tar.gz](https://github.com/ViennaRSS/vienna-rss/files/424043/Viennatest616-678.tar.gz)

**Comment by johnrclarke** [comment]
Thanks, I've tried it but it didn't change the behaviour.

**Comment by josh64x2** [comment]
So I tried it on 10.8.5 and I couldn't reproduce as per the video. However, it does show 1 article unread and when I filter to only show the unread articles the filter is blank.

Installing a 10.9 system now to test as well...

**Comment by josh64x2** [comment]
Sorry, I had a little delay. Hopefully can finish this by the end of the weekend!

**Comment by josh64x2** [comment]
Also unable to reproduce with 10.9 😦 
Any ideas?
